steps:
  build-feature:
    image: woodpeckerci/plugin-docker-buildx
    settings:
      repo: ${CI_REPO}
      tags: "hotfix-${CI_COMMIT_BRANCH##hotfix/}"
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
when:
  branch: hotfix/*
  event: push
