steps:
  install:
    image: danlynn/ember-cli:6.1.0-node_22.12
    commands:
      - npm ci
  lint:js:
    image: danlynn/ember-cli:6.1.0-node_22.12
    commands:
      - npm run lint:js
  lint:hbs:
    image: danlynn/ember-cli:6.1.0-node_22.12
    commands:
      - npm run lint:hbs
  lint:dependencies:
    image: danlynn/ember-cli:6.1.0-node_22.12
    commands:
      - npm run lint:css
  test:
    image: danlynn/ember-cli:6.1.0-node_22.12
    commands:
      - npm run test:ember
when:
  event: pull_request
