pipeline:
  install:
    image: danlynn/ember-cli:4.7.0-node_16.17
    commands:
      - npm ci
  lint:js:
    image: danlynn/ember-cli:4.7.0-node_16.17
    commands:
      - npm run lint:js
  lint:hbs:
    image: danlynn/ember-cli:4.7.0-node_16.17
    commands:
      - npm run lint:hbs
  lint:css:
    image: danlynn/ember-cli:4.2.0-node_16.14
    commands:
      - npm run lint:css
  test:
    image: danlynn/ember-cli:4.7.0-node_16.17
    commands:
      - npm run test:ember
when:
  event: pull_request
